# Generated by Django 5.1.1 on 2024-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_download_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='download_time',
            field=models.IntegerField(null=True),
        ),
    ]
