# Generated by Django 5.1.1 on 2024-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_download_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_summarized',
            field=models.BooleanField(null=True),
        ),
    ]
