# Generated by Django 4.2.16 on 2024-11-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_transcribing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='gpt_input_token_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='gpt_model_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='gpt_output_token_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_char_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_token_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_word_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='trancript_from',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='trancript_token_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_character_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_chunks',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_word_count',
            field=models.IntegerField(null=True),
        ),
    ]
