# Generated by Django 4.2.16 on 2024-11-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_summary_gpt_input_token_count_summary_gpt_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='trancript_from',
            new_name='transcript_from',
        ),
    ]
