# Generated by Django 4.2.16 on 2024-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_rename_trancript_token_count_video_transcript_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_in_playlist',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_id',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_order',
            field=models.IntegerField(null=True),
        ),
    ]
