# Generated by Django 5.1.1 on 2024-10-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('title', models.CharField()),
                ('transcript', models.CharField()),
                ('audio', models.CharField()),
                ('description', models.CharField()),
                ('pub_date', models.DateTimeField(verbose_name='Date published on YouTube')),
                ('channel', models.CharField()),
                ('download_start_date', models.DateTimeField()),
                ('download_end_date', models.DateTimeField()),
                ('download_time', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('is_summarized', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.CharField()),
                ('date', models.DateTimeField()),
                ('summary_start_date', models.DateTimeField()),
                ('summary_end_date', models.DateTimeField()),
                ('summary_time', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
