# Generated by Django 5.1.1 on 2024-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='download_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='download_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date published on YouTube'),
        ),
    ]
