# Generated by Django 5.1.1 on 2024-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_transcribing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcribing_time',
            field=models.IntegerField(null=True),
        ),
    ]
