# Generated by Django 4.2.16 on 2024-11-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_rename_trancript_from_video_transcript_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='trancript_token_count',
            new_name='transcript_token_count',
        ),
    ]
