# Generated by Django 4.2.16 on 2025-02-07 13:48

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_video_is_in_playlist_video_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript_embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
