# Generated by Django 4.2.16 on 2025-02-07 14:25

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_alter_video_transcript_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcript_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
